/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import dao.CursoDao;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Curso;
/**
 *
 * @author 201811640024
 */
public class Cursosdeseja extends javax.swing.JFrame {
 private List<Curso> listaB = new ArrayList<>();
    /**
     * Creates new form Cursosdeseja
     */
    public Cursosdeseja() {
        
        initComponents();
        setSize(914, 644);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaHein = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        campoPES = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        tabelaHein.setBackground(new java.awt.Color(255, 198, 89));
        tabelaHein.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tabelaHein.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Curso", "Área e atuação", "Carga Horaria", "Horario de aulas", "Valor total do curso", "Mensalidade", "Número de vagas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaHein);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 130, 880, 400);

        jButton1.setBackground(new java.awt.Color(255, 198, 89));
        jButton1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        jButton1.setText("Cadastrar um estudante");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 560, 180, 30);

        jButton2.setBackground(new java.awt.Color(255, 198, 89));
        jButton2.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        jButton2.setText("Cadastrar um Instrutor");
        getContentPane().add(jButton2);
        jButton2.setBounds(270, 560, 190, 30);

        jButton3.setBackground(new java.awt.Color(255, 198, 89));
        jButton3.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        jButton3.setText("Voltar na tela de início");
        getContentPane().add(jButton3);
        jButton3.setBounds(520, 560, 170, 30);

        jButton4.setBackground(new java.awt.Color(255, 198, 89));
        jButton4.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        jButton4.setText("Exluir curso");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(740, 560, 130, 30);

        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(51, 80, 40, 20);

        campoPES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPESActionPerformed(evt);
            }
        });
        getContentPane().add(campoPES);
        campoPES.setBounds(90, 80, 130, 30);

        jButton5.setText("Pesquisar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(700, 80, 90, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Telas do VH Cursos.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-2, -5, 900, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        //criar o DAO para cessar ao BD
        CursoDao dao = new CursoDao();
        //chama metodo de recuperação e armazena o retorno
        listaB.clear();
        listaB= dao.recuperaCurs();
        //mostra na tabela, recuperar o medel da tabela
        DefaultTableModel model = (DefaultTableModel) tabelaHein.getModel();
        //percorrer a lista de retorno
        for (Curso c : listaB) {
            //usar o model para add uma linha na tabela
            model.addRow(new Object[]{c.getNome(), c.getCodigo(), c.getArea(), c.getCargaHoraria(), c.getHorarioAula(),
            c.getValorCurso(), c.getValorMensalidade()});
        }
        
        
        
        
        
        
    }//GEN-LAST:event_formWindowOpened

    private void campoPESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPESActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
         CursoDao dao = new CursoDao();
        listaB = dao.pesquisaCurso(campoPES.getText());
        DefaultTableModel model = (DefaultTableModel) tabelaHein.getModel();

        model.setNumRows(0);
        for (Curso c : listaB) {
            model.addRow(new Object[]{c.getNome(), c.getCodigo(), c.getArea(), c.getCargaHoraria(), c.getHorarioAula(),
            c.getValorCurso(), c.getValorMensalidade()});
        }
        
        
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cursosdeseja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cursosdeseja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cursosdeseja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cursosdeseja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cursosdeseja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoPES;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaHein;
    // End of variables declaration//GEN-END:variables
}
