/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.CursoDao;
import model.Curso;

/**
 *
 * @author 201811640024
 */
public class Cursos extends javax.swing.JFrame {

    /**
     * Creates new form Cursos
     */
    public Cursos() {
        initComponents();
        setSize(914, 644);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ccodigo = new javax.swing.JTextField();
        cnome = new javax.swing.JTextField();
        ccargah = new javax.swing.JTextField();
        chorario = new javax.swing.JTextField();
        cvalorc = new javax.swing.JTextField();
        cnumv = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cvalorm = new javax.swing.JTextField();
        carea = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        jLabel2.setText("Preço:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel1.setText("Código:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 250, 53, 20);

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel4.setText("Nome:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(170, 140, 46, 20);

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel5.setText("Carga horária:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(170, 350, 98, 20);

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel6.setText("Horário de Aulas:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(170, 300, 120, 20);

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel7.setText("Valor do Curso:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(170, 410, 107, 20);

        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel8.setText("Valor da Mensalidade:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(170, 520, 154, 20);
        getContentPane().add(ccodigo);
        ccodigo.setBounds(290, 240, 200, 30);
        getContentPane().add(cnome);
        cnome.setBounds(250, 140, 186, 30);
        getContentPane().add(ccargah);
        ccargah.setBounds(300, 350, 190, 30);

        chorario.setText("Ex: 00:00 - 00:00");
        chorario.setToolTipText("");
        chorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chorarioActionPerformed(evt);
            }
        });
        getContentPane().add(chorario);
        chorario.setBounds(300, 300, 250, 30);

        cvalorc.setText("Digite apenas com números e pontos (.)");
        cvalorc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvalorcActionPerformed(evt);
            }
        });
        getContentPane().add(cvalorc);
        cvalorc.setBounds(300, 410, 270, 30);

        cnumv.setText("Digite apenas números");
        cnumv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnumvActionPerformed(evt);
            }
        });
        getContentPane().add(cnumv);
        cnumv.setBounds(310, 460, 170, 30);

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel9.setText("Número de Vagas:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(170, 460, 128, 20);

        cvalorm.setText("Digite apenas com números e pontos (.)");
        getContentPane().add(cvalorm);
        cvalorm.setBounds(330, 520, 240, 30);

        carea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                careaActionPerformed(evt);
            }
        });
        getContentPane().add(carea);
        carea.setBounds(290, 190, 190, 30);

        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel10.setText("Aréa de atuação:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(170, 190, 120, 20);

        btnCadastrar.setBackground(new java.awt.Color(255, 198, 89));
        btnCadastrar.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(730, 540, 120, 40);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/4.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 898, 605);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void careaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_careaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_careaActionPerformed

    private void chorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chorarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chorarioActionPerformed

    private void cnumvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnumvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnumvActionPerformed

    private void cvalorcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvalorcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cvalorcActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        Curso c = new Curso();
        c.setNome(cnome.getText());
        c.setArea(carea.getText());
        c.setCodigo(ccodigo.getText());
        c.setCargaHoraria(ccargah.getText());
        c.setValorCurso(Float.parseFloat(cvalorc.getText()));
        c.setNumeroVagas(Integer.parseInt(cnumv.getText()));
        c.setValorMensalidade(Float.parseFloat(cvalorm.getText()));
        c.setHorarioAula(chorario.getText());
        CursoDao dao = new CursoDao();
        dao.cadastrar(c);
        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cursos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JTextField carea;
    private javax.swing.JTextField ccargah;
    private javax.swing.JTextField ccodigo;
    private javax.swing.JTextField chorario;
    private javax.swing.JTextField cnome;
    private javax.swing.JTextField cnumv;
    private javax.swing.JTextField cvalorc;
    private javax.swing.JTextField cvalorm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
