/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.EstudanteDao;
import model.Estudante;

/**
 *
 * @author 201811640024
 */
public class Estudantes extends javax.swing.JFrame {

    /**
     * Creates new form Aluno
     */
    public Estudantes() {
        initComponents();
        setSize(914, 644);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        eNome = new javax.swing.JTextField();
        eIdade = new javax.swing.JTextField();
        eSexo = new javax.swing.JTextField();
        eTelefone = new javax.swing.JTextField();
        eCpf = new javax.swing.JTextField();
        eEndereco = new javax.swing.JTextField();
        eRg = new javax.swing.JTextField();
        btnGravar = new javax.swing.JButton();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 160, 50, 20);

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel3.setText("Sexo:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 240, 40, 20);

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel4.setText("Idade:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 200, 50, 20);

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel5.setText("Telefone:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 400, 70, 20);

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel6.setText("RG:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(100, 320, 30, 20);

        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel8.setText("CPF:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(100, 280, 50, 20);

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel9.setText("Endereço:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(100, 360, 70, 20);

        eNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eNomeActionPerformed(evt);
            }
        });
        getContentPane().add(eNome);
        eNome.setBounds(160, 160, 520, 20);

        eIdade.setText("Digite apenas números");
        eIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eIdadeActionPerformed(evt);
            }
        });
        getContentPane().add(eIdade);
        eIdade.setBounds(160, 200, 150, 20);

        eSexo.setText("Digite MASCULINO ou FEMININO");
        eSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eSexoActionPerformed(evt);
            }
        });
        getContentPane().add(eSexo);
        eSexo.setBounds(160, 240, 520, 20);

        eTelefone.setText("Digite o ddd entre parenteses (**) e digite o número com o traço (-)");
        eTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eTelefoneActionPerformed(evt);
            }
        });
        getContentPane().add(eTelefone);
        eTelefone.setBounds(180, 400, 500, 20);

        eCpf.setText("Digite com pontos(.) e traços (-)");
        getContentPane().add(eCpf);
        eCpf.setBounds(160, 280, 520, 20);
        getContentPane().add(eEndereco);
        eEndereco.setBounds(180, 360, 500, 20);

        eRg.setText("Digite com pontos(.) e traços(-)");
        getContentPane().add(eRg);
        eRg.setBounds(160, 320, 520, 20);

        btnGravar.setBackground(new java.awt.Color(255, 198, 89));
        btnGravar.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnGravar.setText("Cadastrar");
        btnGravar.setBorderPainted(false);
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGravar);
        btnGravar.setBounds(690, 550, 130, 40);

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3.png"))); // NOI18N
        getContentPane().add(Fundo);
        Fundo.setBounds(0, 0, 898, 605);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eIdadeActionPerformed

    private void eSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eSexoActionPerformed

    private void eTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eTelefoneActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
      Estudante e = new Estudante();
        e.setNome(eNome.getText());
        e.setIdade(Integer.parseInt(eIdade.getText()));
        e.setSexo(eSexo.getText());
        e.setCpf(eCpf.getText());
        e.setRg(eRg.getText());
       e.setEndereco(eEndereco.getText());
        e.setTelefone(eTelefone.getText());
        EstudanteDao dao = new EstudanteDao();
        dao.cadastrar(e);
    }//GEN-LAST:event_btnGravarActionPerformed

    private void eNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estudantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fundo;
    private javax.swing.JButton btnGravar;
    private javax.swing.JTextField eCpf;
    private javax.swing.JTextField eEndereco;
    private javax.swing.JTextField eIdade;
    private javax.swing.JTextField eNome;
    private javax.swing.JTextField eRg;
    private javax.swing.JTextField eSexo;
    private javax.swing.JTextField eTelefone;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables


        
    

}
