/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Estudante;
import dao.EstudanteDao;
/**
 *
 * @author 201811640024
 */
public class PesEstudante extends javax.swing.JFrame {
private List<Estudante> listaB = new ArrayList<>();
    /**
     * Creates new form PesEstudante
     */
    public PesEstudante() {
        initComponents();
         setSize(914, 644);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        campoPES = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnPES = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaHein = new javax.swing.JTable();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 100, 50, 20);
        getContentPane().add(campoPES);
        campoPES.setBounds(290, 90, 370, 30);

        jButton1.setBackground(new java.awt.Color(255, 198, 89));
        jButton1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jButton1.setText("Voltar ao início");
        getContentPane().add(jButton1);
        jButton1.setBounds(746, 570, 137, 29);

        btnPES.setBackground(new java.awt.Color(255, 198, 89));
        btnPES.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        btnPES.setText("Pesquisar");
        btnPES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPESActionPerformed(evt);
            }
        });
        getContentPane().add(btnPES);
        btnPES.setBounds(680, 90, 90, 25);

        jButton3.setBackground(new java.awt.Color(255, 198, 89));
        jButton3.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jButton3.setText("Excluir");
        getContentPane().add(jButton3);
        jButton3.setBounds(10, 570, 90, 29);

        tabelaHein.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Sexo", "Idade", "CPF", "RG", "Endereço", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaHein);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 130, 870, 420);

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/6.png"))); // NOI18N
        getContentPane().add(Fundo);
        Fundo.setBounds(-2, 0, 900, 605);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       EstudanteDao dao = new EstudanteDao();
        //chama metodo de recuperação e armazena o retorno
        listaB.clear();
        listaB= dao.recuperaEs();
        //mostra na tabela, recuperar o medel da tabela
        DefaultTableModel model = (DefaultTableModel) tabelaHein.getModel();
        //percorrer a lista de retorno
        for (Estudante e : listaB) {
            //usar o model para add uma linha na tabela
            model.addRow(new Object[]{e.getNome(),e.getSexo(), e.getIdade(), e.getCpf(), e.getRg(), e.getEndereco(), e.getTelefone()});
        }
        
        
        
        
    }//GEN-LAST:event_formWindowActivated

    private void btnPESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPESActionPerformed
        EstudanteDao dao = new EstudanteDao();
        listaB = dao.pesquisaCurso(campoPES.getText());
        DefaultTableModel model = (DefaultTableModel) tabelaHein.getModel();

        model.setNumRows(0);
        for (Estudante e : listaB) {
            model.addRow(new Object[]{e.getNome(),e.getSexo(), e.getIdade(), e.getCpf(), e.getRg(), e.getEndereco(), e.getTelefone()});
        }
    }//GEN-LAST:event_btnPESActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesEstudante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesEstudante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesEstudante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesEstudante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesEstudante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fundo;
    private javax.swing.JButton btnPES;
    private javax.swing.JTextField campoPES;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaHein;
    // End of variables declaration//GEN-END:variables
}
